print ("Hi Team. How are you doing today?")
print ("Hello")
print ("Hi Susan. Endlich geschafft! Jetzt funktioniert es.")
print ("Hey zusammen, ich probiere jetzt auch mal mein Glück")
print ("Supi! Laüft würde ich sagen! Damit ist dieses Projektchen beendet..")